### ISSUE TITLE
'ArtifactoryPath' object has no attribute 'download_stats'

### ISSUE THREAD

**Issue by JohnChain** [devopshq/artifactory#323]
When I run the sample code in README， I get the following error:

``` python
from artifactory import ArtifactoryPath

path = ArtifactoryPath(
    "http://repo.jfrog.org/artifactory/distributions/org/apache/tomcat/apache-tomcat-7.0.11.tar.gz"
)

# Get FileStat
download_stat = path.download_stats()
print(download_stat)
print(download_stat.last_downloaded)
print(download_stat.last_downloaded_by)
print(download_stat.download_count)
print(download_stat.remote_download_count)
print(download_stat.remote_last_downloaded)
print(download_stat.uri)
````

```
C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe D:/dreame/platformautotest/service/jfrog/jfrog.py
Traceback (most recent call last):
  File "D:\dreame\platformautotest\service\jfrog\jfrog.py", line 8, in <module>
    download_stat = path.download_stats()
AttributeError: 'ArtifactoryPath' object has no attribute 'download_stats'

Process finished with exit code 1
```

**Comment by beliaev-maksim** [comment]
What is the version of this library you use?

**Comment by JohnChain** [comment]
I find "download_stats' was added 9days ago, and after upgrading to 0.8.0, the sample code works fine.

thanks~
