### ISSUE TITLE
Potential Python 3.10 incompatibility - '_NormalAccessor' object has no attribute 'is_dir'

### ISSUE THREAD

**Issue by testworksau** [devopshq/artifactory#317]
We are running our builds on Windows with Python versions 3.6, 3.7, 3.8, and 3.9.

We've just added 3.10 to the mix and have found our build is now failing with the following error:

```
path.deploy_file(file_addr)
--
  | File "C:\python\lib\site-packages\artifactory.py", line 1753, in deploy_file
  | if target.is_dir():
  | File "C:\python\lib\site-packages\artifactory.py", line 1636, in is_dir
  | return self._accessor.is_dir(self)
  | AttributeError: '_NormalAccessor' object has no attribute 'is_dir'. Did you mean: 'listdir'?
```

I've not had time to look any further into the cause of the issue, just wanted to report the problem with `dohq-artifactory-0.7.742` and Python `3.10.0` (`x86`)

**Comment by beliaev-maksim** [comment]
try `pip install dohq-artifactory==0.8.0.dev0`

**Comment by testworksau** [comment]
`0.8.0.dev0` works fine - thanks @beliaev-maksim 🙏🏼
