### ISSUE TITLE
Cannot import name 'ArtifactorySaaSPath' from 'artifactory'

### ISSUE THREAD

**Issue by ricardo-molina** [devopshq/artifactory#355]
I am working with `dohq-artifactory==0.8.0` and `artifactory==0.1.17` in a Flask 2.1.2 application using Python 3.9.

I try importing `ArtifactorySaaSPath` like this: `from artifactory import ArtifactorySaaSPath` and I get this error:
```
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/jfrog_api.py", line 3, in <module>
    app = create_app()
  File "/app/api/app.py", line 21, in create_app
    from api import models
  File "/app/api/models.py", line 5, in <module>
    from artifactory import ArtifactorySaaSPath
ImportError: cannot import name 'ArtifactorySaaSPath' from 'artifactory' (/usr/local/lib/python3.9/dist-packages/artifactory.py)
```

Any idea what's going on, please?
Thank you.

**Comment by beliaev-maksim** [comment]
Modules are clashing

Uninstall `artifactory`, which is legacy
