### PR TITLE
Python 3.13 compatability

### LINKED ISSUE #470: Python 3.13 compatibility
With #463 the library works on Python 3.12 (#430), but not on Python 3.13 yet:

```
AttributeError: module 'pathlib' has no attribute 'posixpath'. Did you mean: 'PosixPath'?
```

_Reported [location](https://github.com/devopshq/artifactory/blob/46728f67725433e06141b5dc36239edf0b614c49/artifactory.py#L447)_

Tested using `master` at 46728f67725433e06141b5dc36239edf0b614c49.

### PR DESCRIPTION
**Pull request by allburov**
Feature branch for Python 3.13 support: https://github.com/devopshq/artifactory/tree/python-3-13
Please run tests with your code (how you use it) and if you find a bug (and the fix, ideally) - create a PR there.
When it's stable enough - we'll merge and release it

```bash
pip install git+https://github.com/devopshq/artifactory@python-3-13
```

Fix #470

### CODE REVIEW

**Review by offa — APPROVED** [review]
Did some basic testing with Python 3.9 - 3.13. Also all of my reported issues work now with 3.13. :+1:

**Comment by Stealthii** [comment]
Confirming support for Python 3.8 through 3.13 with our library that makes extensive use of this, including unit tests 👍

**Comment by allburov** [comment]
Let's set the deadline for Python 3.13 to **April 8**.
Please test the PR proposed for **Python 3.13** and **older** before then🙏

https://github.com/devopshq/artifactory/pull/474

```
pip install git+https://github.com/devopshq/artifactory@python-3-13
```

**Comment by offa** [comment]
Tested on Python 3.13 to 3.10; no issues on my use cases – deployment, search etc. works. :+1:
